// The 16 curses. `combo` is the five answers that give the curse, in question
// order: [trait, follow, color, creature, weakness] (ids from questions.js).
// `icon` is a key of ICONS (icons.js) - the picture shown on the result card.

export const CURSES = [
  {
    id: 'watcher',
    number: 1,
    name: 'THE WATCHER',
    emoji: '👁️',
    combo: ['curious', 'instinct', 'purple', 'ghost', 'overthinking'],
    power: 'Observation',
    weakness: 'Overthinking',
    curse: 'You notice things nobody else notices, but you can never stop looking for answers.',
    omen: 'The thing you are watching has been watching you too.',
    icon: 'mummy',
  },
  {
    id: 'bloodbound',
    number: 2,
    name: 'THE BLOODBOUND',
    emoji: '🩸',
    combo: ['fearless', 'people', 'red', 'vampire', 'anger'],
    power: 'Influence',
    weakness: 'Anger',
    curse: 'People are naturally drawn to you, but your emotions become dangerous when pushed too far.',
    omen: 'Someone will follow you into the dark.',
    icon: 'vampire',
  },
  {
    id: 'oracle',
    number: 3,
    name: 'THE ORACLE',
    emoji: '🔮',
    combo: ['calm', 'logic', 'green', 'witch', 'curiosity'],
    power: 'Foresight',
    weakness: 'Curiosity',
    curse: 'You can see patterns before they happen, but knowing the future makes you unable to leave it alone.',
    omen: 'You already know what happens next.',
    icon: 'cauldron',
  },
  {
    id: 'night-runner',
    number: 4,
    name: 'THE NIGHT RUNNER',
    emoji: '🦇',
    combo: ['fearless', 'instinct', 'black', 'bat', 'fear'],
    power: 'Survival',
    weakness: 'Fear',
    curse: 'Darkness makes you stronger, but the one thing you fear is always one step behind you.',
    omen: "Run fast. It already knows where you're going.",
    icon: 'bat',
  },
  {
    id: 'hollow',
    number: 5,
    name: 'THE HOLLOW',
    emoji: '👻',
    combo: ['calm', 'people', 'black', 'ghost', 'fear'],
    power: 'Disappearing',
    weakness: 'Fear',
    curse: 'You can become invisible in any crowd, but sometimes people forget you were ever there.',
    omen: "Someone remembers you. Someone doesn't.",
    icon: 'ghost',
  },
  {
    id: 'trickster',
    number: 6,
    name: 'THE TRICKSTER',
    emoji: '🟢',
    combo: ['chaotic', 'luck', 'green', 'witch', 'curiosity'],
    power: 'Chaos',
    weakness: 'Curiosity',
    curse: 'Luck bends around you, but every lucky event comes with a strange price.',
    omen: "You got what you wanted. That's the problem.",
    icon: 'jack-o-lantern',
  },
  {
    id: 'puppeteer',
    number: 7,
    name: 'THE PUPPETEER',
    emoji: '🕷️',
    combo: ['curious', 'people', 'purple', 'witch', 'fear'],
    power: 'Manipulation',
    weakness: 'Fear',
    curse: 'You understand people too well. Eventually, you may stop knowing whether they are choosing freely.',
    omen: 'Someone is pulling a string. It might be you.',
    icon: 'spider',
  },
  {
    id: 'wildfire',
    number: 8,
    name: 'THE WILDFIRE',
    emoji: '🔥',
    combo: ['chaotic', 'instinct', 'red', 'vampire', 'anger'],
    power: 'Destruction',
    weakness: 'Anger',
    curse: 'You act before thinking and turn every spark into a fire.',
    omen: 'Whatever you touch tonight may not survive.',
    icon: 'skull',
  },
  {
    id: 'whisperer',
    number: 9,
    name: 'THE WHISPERER',
    emoji: '🌫️',
    combo: ['curious', 'logic', 'black', 'ghost', 'overthinking'],
    power: 'Secrets',
    weakness: 'Overthinking',
    curse: 'You hear truths nobody says out loud. Once you hear them, you cannot forget them.',
    omen: "Someone is about to tell you something they shouldn't.",
    icon: 'black-raven',
  },
  {
    id: 'fortune-eater',
    number: 10,
    name: 'THE FORTUNE EATER',
    emoji: '🍀',
    combo: ['chaotic', 'luck', 'green', 'bat', 'overthinking'],
    power: 'Luck',
    weakness: 'Overthinking',
    curse: 'Impossible things happen in your favor, but you never know when your luck will run out.',
    omen: 'Tonight, luck is on your side. Probably.',
    icon: 'jack-o-lantern',
  },
  {
    id: 'gravetouched',
    number: 11,
    name: 'THE GRAVETOUCHED',
    emoji: '⚰️',
    combo: ['calm', 'instinct', 'black', 'ghost', 'curiosity'],
    power: 'Death Sense',
    weakness: 'Curiosity',
    curse: 'You can sense when something is about to end. The problem is that you always want to know why.',
    omen: 'Something is ending. You already know what.',
    icon: 'gravestone',
  },
  {
    id: 'red-veil',
    number: 12,
    name: 'THE RED VEIL',
    emoji: '🩸',
    combo: ['fearless', 'logic', 'red', 'vampire', 'overthinking'],
    power: 'Focus',
    weakness: 'Overthinking',
    curse: 'Nothing can distract you once you choose a target, but you may chase it far beyond reason.',
    omen: "Once you start, you won't know when to stop.",
    icon: 'zombie-hand',
  },
  {
    id: 'moon-hex',
    number: 13,
    name: 'THE MOON HEX',
    emoji: '🌙',
    combo: ['calm', 'luck', 'purple', 'witch', 'fear'],
    power: 'Protection',
    weakness: 'Fear',
    curse: 'Strange coincidences protect you from danger, but only when you trust the signs.',
    omen: 'The moon has warned you once.',
    icon: 'witch-hat',
  },
  {
    id: 'hunter',
    number: 14,
    name: 'THE HUNTER',
    emoji: '🦇',
    combo: ['fearless', 'logic', 'black', 'bat', 'anger'],
    power: 'Precision',
    weakness: 'Anger',
    curse: 'You rarely miss what you are looking for. Your problem is what happens after you find it.',
    omen: 'You found them. Now what?',
    icon: 'werewolf',
  },
  {
    id: 'mirror-soul',
    number: 15,
    name: 'THE MIRROR SOUL',
    emoji: '🪞',
    combo: ['curious', 'people', 'purple', 'ghost', 'curiosity'],
    power: 'Adaptation',
    weakness: 'Curiosity',
    curse: 'You naturally become what people expect from you, until you forget who you were before them.',
    omen: 'Look carefully. That reflection may not be yours.',
    icon: 'mummy',
  },
  {
    id: 'crowned-one',
    number: 16,
    name: 'THE CROWNED ONE',
    emoji: '👑',
    combo: ['fearless', 'people', 'red', 'witch', 'fear'],
    power: 'Command',
    weakness: 'Fear',
    curse: 'People listen when you speak, but leadership attracts things that want to see you fall.',
    omen: 'Everyone follows the crown. Something follows you.',
    icon: 'skull',
  },
]

// Card background per colour answer (the purple is the one from the Figma card).
export const CARD_COLORS = {
  purple: '#A81F9D',
  red: '#C62828',
  green: '#12A868',
  black: '#1B1B22',
}
